CC = clang 
CFLAGS = -g -Wall

all: bitwise_operators
program: bitwise_operators.o
program.o: bitwise_operators.c

clean:
	rm -f bitwise_operators bitwise_operators.o
run: bitwise_operators
	./bitwise_operators

